// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfx7URdT_y_bCVckRK_ySa-OeWqAGeNjI',
    appId: '1:138889193514:web:31f45eda30124ce1173b53',
    messagingSenderId: '138889193514',
    projectId: 'finance-3ecaa',
    authDomain: 'finance-3ecaa.firebaseapp.com',
    storageBucket: 'finance-3ecaa.firebasestorage.app',
    measurementId: 'G-H9MQ7WH0LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdK4ACPrcVAN2F-NYS8gO_cPewhOMDb5Y',
    appId: '1:138889193514:android:e80403a1a670ad67173b53',
    messagingSenderId: '138889193514',
    projectId: 'finance-3ecaa',
    storageBucket: 'finance-3ecaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTAXcD3WpmvxD6L7H66YtaQgHRf_Ydvc',
    appId: '1:138889193514:ios:e32f04f94363132a173b53',
    messagingSenderId: '138889193514',
    projectId: 'finance-3ecaa',
    storageBucket: 'finance-3ecaa.firebasestorage.app',
    iosClientId: '138889193514-f3gq2lfbbrbmh6bjo04g1666u2cruien.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHTAXcD3WpmvxD6L7H66YtaQgHRf_Ydvc',
    appId: '1:138889193514:ios:e32f04f94363132a173b53',
    messagingSenderId: '138889193514',
    projectId: 'finance-3ecaa',
    storageBucket: 'finance-3ecaa.firebasestorage.app',
    iosClientId: '138889193514-f3gq2lfbbrbmh6bjo04g1666u2cruien.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfx7URdT_y_bCVckRK_ySa-OeWqAGeNjI',
    appId: '1:138889193514:web:8f9391ffe9aef90e173b53',
    messagingSenderId: '138889193514',
    projectId: 'finance-3ecaa',
    authDomain: 'finance-3ecaa.firebaseapp.com',
    storageBucket: 'finance-3ecaa.firebasestorage.app',
    measurementId: 'G-RHGFLS3N6J',
  );
}
